#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/atm_db
      - DB_USER=postgres
      - DB_PASSWORD=111111

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=atm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111111
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
